# Generated by Django 5.2.8 on 2026-07-09 18:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Customer ID')),
                ('nama_lengkap', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('nomor_wa', models.CharField(max_length=20, verbose_name='Nomor WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_paket', models.CharField(max_length=200, verbose_name='Nama Paket')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('harga_paket', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Harga Paket (Rp)')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['harga_paket'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_invoice', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Nomor Invoice')),
                ('tanggal_dibuat', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Dibuat')),
                ('total_tagihan', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Total Tagihan (Rp)')),
                ('nominal_terbayar', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Nominal Terbayar (Rp)')),
                ('sisa_tagihan', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=15, verbose_name='Sisa Tagihan (Rp)')),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Pembayaran'), ('dp', 'DP Terbayar'), ('proses', 'Proses'), ('lunas', 'Lunas'), ('overdue', 'Overdue')], default='menunggu', max_length=20, verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='payments.client', verbose_name='Client')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='payments.package', verbose_name='Package')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-tanggal_dibuat'],
            },
        ),
        migrations.CreateModel(
            name='VendorTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_vendor', models.CharField(help_text='Contoh: Venue, Katering, MUA', max_length=200, verbose_name='Nama Vendor')),
                ('status_pembayaran', models.CharField(choices=[('menunggu', 'Menunggu'), ('selesai', 'Selesai')], default='menunggu', max_length=20, verbose_name='Status Pembayaran')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='payments.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Vendor Tracker',
                'verbose_name_plural': 'Vendor Trackers',
                'ordering': ['nama_vendor'],
            },
        ),
    ]
