# Generated by Django 5.2.8 on 2026-07-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortracker',
            name='harga_vendor',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Nominal harga dari vendor ini', max_digits=15, verbose_name='Harga Vendor (Rp)'),
        ),
        migrations.AddField(
            model_name='vendortracker',
            name='nominal_dibayar',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Nominal yang sudah dibayarkan admin ke vendor', max_digits=15, verbose_name='Nominal Dibayar ke Vendor (Rp)'),
        ),
    ]
