# Generated by Django 5.2.8 on 2026-07-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_vendortracker_harga_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bisnis', models.CharField(default='Berkat Wedding Organizer', max_length=200)),
                ('nama_bank', models.CharField(default='Bank Central Asia (BCA)', max_length=100)),
                ('nomor_rekening', models.CharField(default='1234567890', max_length=50)),
                ('atas_nama_rekening', models.CharField(default='Berkat Wedding Organizer', max_length=100)),
                ('nomor_wa_konfirmasi', models.CharField(default='62895337452311', max_length=20)),
            ],
            options={
                'verbose_name': 'Business Settings',
                'verbose_name_plural': 'Business Settings',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nomor Rekening'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Atas Nama Rekening'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nama Bank'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='wa_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nomor WhatsApp Konfirmasi'),
        ),
    ]
