# Generated by Django 5.2.8 on 2026-07-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_businesssettings_invoice_bank_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendortracker',
            name='harga_vendor',
        ),
        migrations.RemoveField(
            model_name='vendortracker',
            name='nominal_dibayar',
        ),
        migrations.AddField(
            model_name='vendortracker',
            name='progress_persen',
            field=models.IntegerField(default=0, help_text='Persentase progress vendor (0-100)', verbose_name='Progress (%)'),
        ),
        migrations.AlterField(
            model_name='vendortracker',
            name='status_pembayaran',
            field=models.CharField(choices=[('menunggu', 'Menunggu'), ('proses', 'Proses'), ('selesai', 'Selesai')], default='menunggu', max_length=20, verbose_name='Status'),
        ),
    ]
