# Generated by Django 5.2.8 on 2026-07-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_vendortracker_harga_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='lokasi',
            field=models.TextField(default='Elegansi Abadi untuk Hari Bahagia Anda.\nJl. Slamet Riyadi No. 450, Solo, Jawa Tengah.'),
        ),
    ]
