# Generated by Django 5.2.8 on 2026-07-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_businesssettings_lokasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='terms_and_conditions',
            field=models.TextField(default='Booking tanpa DP = No Keep tanggal & vendor\nBooking min. DP 10% dari package yang diambil\nBiaya boleh dicicil tiap bulannya hingga pelunasan h-7\nPelunasan H-7 hari acara berlangsung\nBiaya diatas belum termasuk charge transportasi bila ada vendor yang dipilih client dari luar kota\nBiaya diatas untuk acara dalam 1 hari yang sama\nUpgrade MC Akad Rp. 300.000'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='request_client',
            field=models.TextField(blank=True, null=True, verbose_name='Request Client'),
        ),
    ]
