# Generated by Django 5.2.8 on 2026-07-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_businesssettings_terms_and_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='email_bisnis',
            field=models.EmailField(default='admin@berkatwo.com', max_length=254),
        ),
    ]
