# Generated by Django 5.2.8 on 2026-07-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_invoicesequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortracker',
            name='dibayar',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Nominal Dibayar (Rp)'),
        ),
        migrations.AddField(
            model_name='vendortracker',
            name='harga',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Harga Vendor (Rp)'),
        ),
        migrations.AddField(
            model_name='vendortracker',
            name='tipe',
            field=models.CharField(choices=[('include', 'Include Paket'), ('add_on', 'Add-on (Tambahan)')], default='include', max_length=20, verbose_name='Tipe Vendor'),
        ),
    ]
