# Generated by Django 5.2.8 on 2026-07-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_vendortracker_dibayar_vendortracker_harga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendortracker',
            name='tipe',
        ),
        migrations.AddField(
            model_name='vendortracker',
            name='dibayar_addon',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Dibayar Add-on (Rp)'),
        ),
        migrations.AddField(
            model_name='vendortracker',
            name='harga_addon',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Harga Add-on (Rp)'),
        ),
        migrations.AddField(
            model_name='vendortracker',
            name='nama_addon',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama Add-on'),
        ),
    ]
